### ISSUE TITLE
Errors building btc canister on apple silicon

### ISSUE THREAD

**Issue by dangdennis** [dfinity/bitcoin-developer-preview#10]
Shared my WIP debugging steps in the discord #s-help channel. https://discord.com/channels/748416164832608337/953588280568479756/974699586251817050

# Issue
I'm encountering errors when attempting to build the `btc` canister on a mac m1 laptop. I've followed the setup docs and encountered typical brew issues related to apple silicon. After resolving the whole brew issue, my latest one involves the lib `wabt-sys`. If you know how to get past, duly appreciate the help.

```
error: failed to add native library /var/folders/33/dxhswk150sx1sblqvj718r700000gn/T/cargo-installjCLJKE/release/build/wabt-sys-db34d7fdf57f8cf5/out/build/libwabt.a: file too small to be an archive

error: could not compile `wabt-sys` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `ic-cdk-optimizer v0.3.1`, intermediate artifacts can be found at `/var/folders/33/dxhswk150sx1sblqvj718r700000gn/T/cargo-installjCLJKE`
```

https://github.com/pepyakin/wabt-rs/issues/78 Seems to be a common problem.

# Request

Can anyone on your team test this repo with an mac m1 machine?

**Comment by dangdennis** [comment]
A workaround for now is to comment out the `ic-cdk-optimizer` within the build scripts.

**Comment by dangdennis** [comment]
For those having issue with brew because Apple silicon installs brew files under /opt/homebrew, try this to have a sort of hack to reuse usr/local prefix

https://apple.stackexchange.com/questions/437618/why-is-homebrew-installed-in-opt-homebrew-on-apple-silicon-macs

**Comment by torates** [comment]
> For those having issue with brew because Apple silicon installs brew files under /opt/homebrew, try this to have a sort of hack to reuse usr/local prefix
> 
> https://apple.stackexchange.com/questions/437618/why-is-homebrew-installed-in-opt-homebrew-on-apple-silicon-macs

Worked for me on my Macbook Air 2022.
